refactor: first commit
eggjs/egg-global-header pull request #1
Opened 2018-03-09 09:35 UTC by XadillaX

2018-03-09 09:39 UTC, popomore commented on README.md
> +  set: {
最好不要用 set

2018-03-09 09:40 UTC, popomore commented on config/config.default.js
> +exports.globalHeader = {
加个 jsdoc

2018-03-09 09:42 UTC, fengmk2 commented on README.md
> +  set: {
直接配置不行？为何要加一层？

2018-03-09 09:43 UTC, popomore approved these changes

2018-03-09 09:44 UTC, atian25 commented on app/middleware/global_header.js
> +  options = Object.assign({}, options);
复制了干嘛?

2018-03-09 09:44 UTC, atian25 commented on app/middleware/global_header.js
> +    return next().then(function() {
这段能在 6 跑?

2018-03-09 09:44 UTC, atian25 commented on app/middleware/global_header.js
> +    return next().then(function() {
还要支持 egg1 和 node 6 么?

2018-03-09 09:44 UTC, XadillaX commented on README.md
> +  set: {
@fengmk2 这个是为了以后扩展

2018-03-09 09:45 UTC, fengmk2 requested changes

2018-03-09 09:45 UTC, fengmk2 commented on app/middleware/global_header.js
> +  return function(ctx, next) {
请使用aa 语法

2018-03-09 09:45 UTC, fengmk2 commented on app/middleware/global_header.js
> +  options = Object.assign({}, options);
没必要copy吧，直接用起来。还方便 mock

2018-03-09 09:46 UTC, XadillaX commented on app/middleware/global_header.js
> +  return function(ctx, next) {
不是你说了要支持低版本吗😂

2018-03-10 08:40 UTC, fengmk2 commented on app/middleware/global_header.js
> +  return function(ctx, next) {
新的功能从 egg 2 开始支持。
内部 chair 1.4 支持 aa 的

2018-03-10 08:41 UTC, fengmk2 commented on README.md
> +  set: {
不要为想不到的未来做扩展，除非你现在就想到了场景。

2018-03-10 08:44 UTC, fengmk2 commented on app/middleware/global_header.js
> +        if (!response.get(key)) {
将 headers 一次性读出来，然后 toLowerCase() 查询，比每次都 response.get 高效

https://github.com/koajs/koa/blob/master/lib/response.js#L46

2018-03-10 08:45 UTC, fengmk2 commented on test/fixtures/apps/header/config/config.default.js
> +    'powered-by': 'xadillax',
改成大写，确保大小写不敏感。

2018-03-10 08:48 UTC, popomore commented on app/middleware/global_header.js
> +  return function(ctx, next) {
1.4 不行的，是 6.0

2018-03-10 08:49 UTC, fengmk2 commented on app/middleware/global_header.js
> +  return function(ctx, next) {
可以强制 install-node 为 8

2018-03-10 08:51 UTC, popomore commented on app/middleware/global_header.js
> +  return function(ctx, next) {
这件事情不做了，直接升级 1.5

2018-03-10 08:51 UTC, popomore commented
这个插件其实可以内置到 egg 里

2018-03-12 02:52 UTC, XadillaX commented on README.md
> +  set: {
比如说

```js
get: {
  token: async val => {
    // 获取用户信息
  }
}
```

2018-03-12 03:01 UTC, XadillaX commented on app/middleware/global_header.js
> +  return function(ctx, next) {
@fengmk2 你这样要强制所有应用升级，包括 Node.js 6 的应用。

2018-03-14 03:10 UTC, XadillaX commented
/ping @popomore @fengmk2

2018-03-14 03:33 UTC, popomore approved these changes

2018-03-14 03:34 UTC, popomore commented
现在就是要 @fengmk2 确认下 set 这个配置

2018-03-14 03:35 UTC, fengmk2 commented on README.md
> +  set: {
还在配置中提供方法，而且是异步方法，严重不同意这样的设计，配置尽量是配置。

2018-03-14 03:35 UTC, fengmk2 commented on README.md
> +  set: {
get 是什么需求？不要超前设计了。

2018-03-14 03:42 UTC, fengmk2 commented on app/middleware/global_header.js
> +  const _set = _setKeys.reduce((ret, key, idx) => {
好复杂，无法就是将 key 转为 lowerCase，没必要这么复杂吧。

headers 的 name 都是小写的。

将要设置的 optionHeaders 做一次初始化，变成 key 是小写的即可。
下面遍历 optionHeaders ，判断 key 不在 response.headers 里面就设置，比现在的实现容易看懂吧。

2018-03-14 12:33 UTC, XadillaX commented on app/middleware/global_header.js
> +  const _set = _setKeys.reduce((ret, key, idx) => {
1. 被告知要用 `for...of`，所以小写 `key` 要存在一个数组里面；
2. 对象的键值对的键名要变成小写。

我再想想怎么写吧。

2018-03-19 02:41 UTC, XadillaX commented
/ping @fengmk2

2018-03-21 02:47 UTC, XadillaX commented
/ping @fengmk2

2018-03-21 05:54 UTC, fengmk2 commented on app/middleware/global_header.js
> +  const optionHeaders = Object.keys(options).reduce((headers, key) => {
一定要写这么复杂么？

2018-03-21 05:56 UTC, fengmk2 commented on app/middleware/global_header.js
> +  return async (ctx, next) => {
中间件还是使用命名函数吧，方便调试，报错知道中间件信息。

2018-03-21 06:00 UTC, fengmk2 commented on app.js
> +  app.config.coreMiddleware.push('globalHeader');
globalHeader 没有配置项，就不添加中间件了。

2018-03-21 06:12 UTC, XadillaX commented on app/middleware/global_header.js
> +  const optionHeaders = Object.keys(options).reduce((headers, key) => {
配置是 Object 的，所以现在做的事情是将 Object 的 `key` 变为小写，生成一个新的 Object，暂时我就想到这个办法 -。 -

2018-03-21 06:14 UTC, XadillaX commented on app/middleware/global_header.js
> +  const optionHeaders = Object.keys(options).reduce((headers, key) => {
```javascript
const optionHeaders = {};
const optionHeaderKeys = [];
for (const key in options) {
  if (!options.hasOwnProperty(key)) continue;
  optionHeaders[key.toLowerCase()] = options[key];
  optionHeaderKeys.push(key.toLowerCase());
}
```

这样呢？

2018-03-21 15:24 UTC, fengmk2 commented on app/middleware/global_header.js
> +  const optionHeaders = Object.keys(options).reduce((headers, key) => {
`if (!options.hasOwnProperty(key)) continue;` 不需要

`optionHeaderKeys.push(key.toLowerCase());` 不需要，下面 for in 循环遍历 optionHeaders 即可，不需要单独的一个 optionsHeaderKeys 数组。

2018-03-21 15:25 UTC, fengmk2 commented on app/middleware/global_header.js
> +  // 将键值对的键名变小写
不要中文注释。

2018-03-22 03:01 UTC, XadillaX commented on app/middleware/global_header.js
> +  const optionHeaders = Object.keys(options).reduce((headers, key) => {
我主要是遵循这个 Lint 来写的，https://eslint.org/docs/rules/guard-for-in。如果不需要关心该 Lint 的话的确可以用 `for...in` 来简化。

2018-03-22 03:10 UTC, XadillaX commented on app/middleware/global_header.js
> +  const optionHeaders = Object.keys(options).reduce((headers, key) => {
几年前被 `for...in` 的非 own property 坑过，所以我之后一直这么写了。

2018-03-23 03:19 UTC, XadillaX commented on app/middleware/global_header.js
> +  const optionHeaders = Object.keys(options).reduce((headers, key) => {
@fengmk2 

1. 我们不能控制使用 Egg.js 的开发者的代码写得怎么样，也不能控制他们用的包怎么样；
2. 如果他们的代码（或者三方库）这么写，就有坑：

   ```js
   // somewhere
   Object.prototype.assign = function() { /** 他们自己的实现 */ };

   // config
   exports.globalHeader = { foo: 'bar' };
   ```

   这个时候在 `for...in` 里面就会多出一个 `assign`。

2018-03-26 05:27 UTC, XadillaX commented
/ping @fengmk2

2018-04-18 04:09 UTC, atian25 commented
ping

2018-05-28 11:27 UTC, XadillaX commented
/ping @fengmk2

2018-05-28 11:28 UTC, fengmk2 commented on app/middleware/global_header.js
> +  for (const key of Object.keys(options)) {
`for (const key in options)` 有什么问题？

2018-05-28 11:30 UTC, fengmk2 commented on app/middleware/global_header.js
> +      if (!headers[key]) {
应该是`!(key in headers)` 吧，value 可以为空字符串

2018-05-28 11:30 UTC, fengmk2 commented on appveyor.yml
> +    - nodejs_version: '9'
10

2018-05-29 03:23 UTC, XadillaX commented on app/middleware/global_header.js
> +  for (const key of Object.keys(options)) {
个人的观点，`for...in` 应当与 `Object.prototype.hasOwnProperty()` 搭配，如：

```javascript
for (const key in options) {
  if (options.hasOwnProperty('key')) {
    // ...
  }
}
```

或者

```javascript
for (const key in options) {
  if (!options.hasOwnProperty('key')) continue;
}
```

> 参考 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in#Iterating_over_own_properties_only 和 [https://eslint.org/docs/rules/guard-for-in](https://eslint.org/docs/rules/guard-for-in)。

不然会有这样的问题，如果一个人项目中（无论是自己还是三方包）改了一些原型链的话（毕竟我以前踩过坑）：

```javascript
Object.prototype.foo = function() {};

const a = { a: 1 };

for (const key in a) console.log(key); // foo, a
for (const key in a) {
  if (!a.hasOwnPrototype(key)) continue;
  console.log(key); // a
}
for (const key of Object.keys(a)) console.log(key); // a
```

2018-05-30 03:13 UTC, XadillaX commented
/ping @fengmk2

2018-05-30 12:46 UTC, fengmk2 commented on app/middleware/global_header.js
> +  for (const key of Object.keys(options)) {
但是你这里的 options 参数，完全不会出现你说的问题。。。

2018-05-30 12:48 UTC, fengmk2 commented on package.json
> +    "version": "8, 9"
`"8, 10"`

2018-05-30 12:49 UTC, fengmk2 approved these changes

2018-05-30 12:49 UTC, merged

2018-05-30 12:50 UTC, fengmk2 commented
@XadillaX 你来发版本吧。